name: Security CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- SAST: CodeQL + Semgrep ---
  sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Install dependencies
        run: npm ci

      - name: Analyze code with CodeQL
        uses: github/codeql-action/analyze@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

  # --- Build ---
  build:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  # --- DAST: ZAP scan ---
  dast:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ghcr.io/zaproxy/zaproxy:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start app
        run: |
          apt-get update && apt-get install -y curl gnupg
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs
          npm ci
          npm start &
          sleep 10

      - name: Run OWASP ZAP scan
        run: |
          zap-full-scan.py \
            -t http://host.docker.internal:3000 \
            -r zap-report.html \
            -J zap-report.json \
            -d -I || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html
