name: CI Security Pipeline (SAST + Burp)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write

jobs:
  sast:
    name: Static Code Analysis (Semgrep)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and Save Report
        run: semgrep --config auto . --json > semgrep_report.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep_report.json

  dast:
    name: Dynamic Scan (Burp Suite)
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Flask
        run: pip install flask

      - name: Run Flask app (main.py)
        run: |
          nohup python main.py &
          sleep 10

      - name: Run Burp Scanner (Docker)
        run: |
          docker run --rm \
            -v $(pwd):/mnt \
            -e BURP_LICENSE_KEY=${{ secrets.BURP_LICENSE_KEY }} \
            burpsuite/professional \
            --project-file=/mnt/project.burp \
            --config-file=/mnt/burp_config.json \
            --report-file=/mnt/burp_report.html \
            --scan-target http://localhost:5000
        env:
          DISPLAY: ":99"
        continue-on-error: true

      - name: Upload Burp Report
        uses: actions/upload-artifact@v4
        with:
          name: burp-report
          path: burp_report.html
