name: CI Security Pipeline

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Code Analysis (Semgrep)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST and Save Report
        # run: semgrep --config auto . --json > semgrep_report.json
        run: semgrep --config auto --exclude "test/*" --severity ERROR --json > semgrep_report.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report  # Простое имя для артефакта
          path: semgrep_report.json

  dast:
    name: Dynamic App Scan (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Убедись, что версия Python доступна

      - name: Install dependencies
        run: |
          pip install flask

      - name: Проверка наличия файла
        run: ls -la

      - name: Run Flask app in background
        run: |
          nohup python main.py &
          sleep 10

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:5000'