name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Analysis (SAST) with Semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config auto .

  build-and-deploy:
    name: Build and Deploy App (Placeholder)
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build step
        run: echo "Build your app here"

      - name: Deploy step
        run: echo "Deploy to staging or use Docker locally"

  dast:
    name: Dynamic Analysis (DAST) with OWASP ZAP
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: 'http://example.com'  # замените на URL вашего развернутого приложения
