name: CI Security Pipeline

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Code Analysis (Semgrep)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST
        run: semgrep --config auto .

  dast:
    name: Dynamic App Scan (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Убедись, что версия Python доступна

      - name: Install dependencies
        run: |
          pip install flask

      - name: Run Flask app in background
        run: |
          nohup python vulnerable_with_false_positives.py &
          sleep 10

      - name: Run OWASP ZAP Docker scan
        run: |
          docker pull owasp/zap2docker-stable  # Загрузка образа OWASP ZAP
          docker run -u zap -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:5000 -g gen.conf -r zap_report.html
        env:
          DISPLAY: ":99"
