name: Security CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sast-semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python (Semgrep requires it)
        uses: actions/setup-python@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep (ignore exit code)
        run: semgrep --config auto --json > semgrep-report.json || true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

  sast-codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Install dependencies
        run: npm install

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dast-zap:
    runs-on: ubuntu-latest
    needs: [sast-semgrep, sast-codeql]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start App
        run: |
          npm start &
          sleep 10

      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:3000'
          fail-action: ignore

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: owasp-zap-report.html
